 -- 시퀀스 삭제
DROP SEQUENCE SEQ_BOOK;
DROP SEQUENCE SEQ_CINEMA;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_MOVIEINFO;
DROP SEQUENCE SEQ_TIMETABLE;

 -- 시퀀스 생성
CREATE SEQUENCE SEQ_BOOK START WITH 101;
CREATE SEQUENCE SEQ_CINEMA START WITH 6;
CREATE SEQUENCE SEQ_MEMBER START WITH 22;
CREATE SEQUENCE SEQ_MOVIEINFO START WITH 21008;
CREATE SEQUENCE SEQ_TIMETABLE START WITH 316;

 -- 테이블의 모든 데이터를 삭제
DELETE FROM BOOK WHERE BOOK_ID IS NOT NULL;
DELETE FROM CINEMA WHERE CINEMA_ID IS NOT NULL;
DELETE FROM MEMBER WHERE MEMBER_NO IS NOT NULL;
DELETE FROM MOVIEINFO WHERE MOVIE_ID IS NOT NULL;
DELETE FROM TIMETABLE WHERE TIME_ID IS NOT NULL;

 -- PK 오름차순으로 MEMBER 테이블 전체 조회
SELECT * FROM BOOK ORDER BY BOOK_ID;
SELECT * FROM CINEMA ORDER BY CINEMA_ID;
SELECT * FROM MEMBER ORDER BY MEMBER_NO;
SELECT * FROM MOVIEINFO ORDER BY MOVIE_ID;
SELECT * FROM TIMETABLE ORDER BY TIME_ID;