/****************************************************
-- 각각의 테이블을 생성하거나 테이블을 삭제하는 명령문
*****************************************************/

 -- MEMBER 테이블 생성
CREATE TABLE MEMBER (
   MEMBER_NO NUMBER CONSTRAINT MEMBER_NO_PK PRIMARY KEY,
   MEMBER_ID VARCHAR2 (45) NOT NULL CONSTRAINT MEMBER_ID_UK UNIQUE,
 MEMBER_NAME VARCHAR2 (45) NOT NULL,
    PASSWORD VARCHAR2 (45) NOT NULL,
       PHONE VARCHAR2 (45),
       EMAIL VARCHAR2 (100)
);

 -- MOVIEINFO 테이블 생성
CREATE TABLE MOVIEINFO (
    MOVIE_ID NUMBER CONSTRAINT MOVIE_ID_PK PRIMARY KEY,
       TITLE VARCHAR2 (100) NOT NULL,
       STORY VARCHAR2 (2000) NOT NULL,
       GRADE VARCHAR2 (45)  NOT NULL
);

 -- CINEAM 테이블 생성
CREATE TABLE CINEMA (
   CINEMA_ID NUMBER CONSTRAINT CINEMA_ID_PK PRIMARY KEY,
      REGION VARCHAR2 (45) NOT NULL,
     C_PHONE VARCHAR2 (45) NOT NULL
);

 -- TIMETABLE 테이블 생성
CREATE TABLE TIMETABLE (
     TIME_ID NUMBER CONSTRAINT TIME_ID_PK PRIMARY KEY,
    MOVIE_ID NUMBER NOT NULL CONSTRAINT MOVIE_ID_FK_TT REFERENCES MOVIEINFO (MOVIE_ID),
    CINEMA_ID NUMBER NOT NULL CONSTRAINT CINEMA_ID_FK_TT REFERENCES CINEMA (CINEMA_ID),
 SCREEN_DATE VARCHAR2 (45) NOT NULL,
 SCREEN_TIME VARCHAR2 (45) NOT NULL
);

 -- BOOK 테이블 생성
CREATE TABLE BOOK (
     BOOK_ID NUMBER CONSTRAINT BOOK_ID_PK PRIMARY KEY,
   CINEMA_ID NUMBER NOT NULL CONSTRAINT CINEMA_ID_FK_B REFERENCES CINEMA (CINEMA_ID),
    MOVIE_ID NUMBER NOT NULL CONSTRAINT MOVIE_ID_FK_B REFERENCES MOVIEINFO (MOVIE_ID),
   MEMBER_NO NUMBER NOT NULL CONSTRAINT MEMBER_NO_FK_B REFERENCES MEMBER (MEMBER_NO),
       PRICE NUMBER NOT NULL,
     TIME_ID NUMBER NOT NULL
);


 -- 모든 테이블을 삭제하기 위한 쿼리문을 불러오는 SELECT 문
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

 -- 위 SELECT 문을 실행하면 아래의 다섯개의 문장이 출력되고 복사하여 전부 실행하면 모든 테이블이 삭제됨
DROP TABLE "CINEMA" CASCADE CONSTRAINTS;
DROP TABLE "MOVIEINFO" CASCADE CONSTRAINTS;
DROP TABLE "TIMETABLE" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "BOOK" CASCADE CONSTRAINTS;